# Generated by Django 5.2 on 2025-05-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('file_doc', models.FileField(blank=True, null=True, upload_to='products/docs/')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='products/pdfs/')),
            ],
        ),
        migrations.AlterField(
            model_name='indicatordownload',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
