# Generated by Django 5.2 on 2025-05-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_indicatordownload_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
